import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import collegelogo from './../../public/logooobbbb.png'
import Image from "next/image";
export const metadata = {
  title: "Feedback form GEC Aurangabad",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body>
       <nav className="navbar">
        {/* <div> <Image src={collegelogo} width={45} alt='GEC Aurangabad logo'  height={45}/> </div> */}
  <div className="navContainer">
    <h2 className="navTitle"> Semester Feedback form</h2>
  </div>
  <ul className="navLinks" style={{display:'flex', gap:8,listStyleType:'none'}}>
    <li><a href="/admin" style={{ color: 'white',textDecoration:'none',listStyleType:'none', margin:8 }}>Admin</a></li>
    <li><a href="/logout" style={{ color: 'white',textDecoration:'none',listStyleType:'none', margin:8 }}>Logout</a></li>
   
  </ul>
</nav>
        {children}
      </body>
    </html>
  );
}
